TicketReservation/Models/Bookingdetails.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TicketReservation.Models
{
    public class Bookingdetails
    {
       // [Range(0, 40000, ErrorMessage = "Enter the salary less than 40000/No negative numbers")]
       [Required]
        public int BookingId { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required]

        public string EmailId { get; set; }
        [Required]

        public int? TrainNo { get; set; }
        [Required]

        [DataType(DataType.Text)]

        public string FromStation { get; set; }
        [Required]

        [DataType(DataType.Text)]

        public string ToStation { get; set; }
        [Required]

        [DataType(DataType.Date)]
        [Remote("DateCheck", "BookingDetail",
               ErrorMessage = "Give Valid Date")]
        public DateTime? JourneyDate { get; set; }
        [Required]

        [Range(0, 50, ErrorMessage = "Enter the seats less than 50/No negative numbers")]

        public int? NoOfSeats { get; set; }
        [Required]

        public string BookingStatus { get; set; }

    }
}

TicketReservation/Controllers/BookingDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using TicketReservation.Models;

namespace TicketReservation.Controllers
{
    public class BookingDetailController : Controller
    {

        string Baseurl = "https://localhost:44381/";

        public static Bookingdetails book = new Bookingdetails();
        public ActionResult BookingDetails()
        {
            /* List<Bookingdetails> BookingInfo = new List<Bookingdetails>();

             using (var client = new HttpClient())
             {
                 //Passing service base url  
                 client.BaseAddress = new Uri(Baseurl);

                 client.DefaultRequestHeaders.Clear();
                 //Define request data format  
                 client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                 //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                 HttpResponseMessage Res = await client.GetAsync("/api/BookingDetails");

                 //Checking the response is successful or not which is sent using HttpClient  
                 if (Res.IsSuccessStatusCode)
                 {
                     //Storing the response details recieved from web api   
                     var bookingResponse = Res.Content.ReadAsStringAsync().Result;

                     //Deserializing the response recieved from web api and storing into the Employee list  
                     BookingInfo = JsonConvert.DeserializeObject<List<Bookingdetails>>(bookingResponse);

                 }
                 //returning the employee list to view  
                 return View(BookingInfo);
             }*/
            return View(book);
        }
        
    
    [HttpGet]
    public async Task<ActionResult> GetBookById(int id)
        {
            
            List<Bookingdetails> book = new List<Bookingdetails>();

            using (var httpClient = new HttpClient())
        {
                
                using (var response = await httpClient.GetAsync("https://localhost:44381/api/BookingDetails/" + id))
                {

                    string apiResponse = await response.Content.ReadAsStringAsync();
                    book = JsonConvert.DeserializeObject<List<Bookingdetails>>(apiResponse);

                }
            }
            return View(book);
        }


        //[HttpGet]
        //public async Task<ActionResult> BookedPassenger(int BookId)
        //{


        //    using (var httpClient = new HttpClient())
        //    {

        //        using (var response = await httpClient.GetAsync("https://localhost:44330/api/TrainDetails/" + BookId ))
        //        {

        //            string apiResponse = await response.Content.ReadAsStringAsync();
        //          //  Train = JsonConvert.DeserializeObject<List<TrainDetail>>(apiResponse);

        //        }


        //    }
        //    return View(Train);



        //}






        public ActionResult AddBookingDetail(int  id,string from,string to,int ClassA, int ClassB, int ClassC,string email)
        {
            TempData["Email"] = email;
            TempData["Tno"] = id;
            TempData["Tf"] = from;
            TempData["Tt"] = to;
            TempData["classA"] = ClassA;
            TempData["classB"] = ClassB;
            TempData["classC"] = ClassC;

            //   Bookingdetails=

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddBookingDetail(Bookingdetails booking,TrainDetail train,Register register)
        {

            string email = (string)TempData.Peek("mail");
            int id = (int)TempData.Peek("Tno");
            string from = (string)TempData.Peek("Tf");
            string to = (string)TempData.Peek("Tt");
            int ClassA = (int)TempData.Peek("classA");
            int ClassB = (int)TempData.Peek("classB");
            int ClassC = (int)TempData.Peek("classC");
            
            booking.FromStation = from;
            booking.TrainNo = id;
            booking.ToStation = to;
            train.SeatAvailA = ClassA - booking.NoOfSeats;
            train.SeatAvailB = ClassB - booking.NoOfSeats;
            train.SeatAvailC = ClassC - booking.NoOfSeats;

            
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(booking), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:44381/api/BookingDetails", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    book = JsonConvert.DeserializeObject<Bookingdetails>(apiResponse);
                }
               
            }
            return RedirectToAction("BookingDetails");
           
        }
        public bool DateCheck(Bookingdetails book)
        {
            if (book.JourneyDate < DateTime.Today)
            {

                return false;
                
            }
            else
            {
                return true;
            }
        }
        [HttpGet]
        public async Task<ActionResult> CancelTicket(int id)
        {
            TempData["BookingId"] = id;
            Bookingdetails e = new Bookingdetails();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44381/api/BookingDetails" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    e = JsonConvert.DeserializeObject<Bookingdetails>(apiResponse);
                }
            }
            return View(e);
        }


        [HttpPost]
        // [ActionName("DeleteEmployee")]
        public async Task<ActionResult> CancelTicket(Bookingdetails book)
        {
            int BookingId = Convert.ToInt32(TempData["BookingId"]);
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync("https://localhost:44381/api/BookingDetails/" + BookingId))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }

            return RedirectToAction("Index");
        }
    }
}

TicketReservation/Controllers/PassengerDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using TicketReservation.Models;

namespace TicketReservation.Controllers
{
    public class PassengerDetailController : Controller
    {
        string Baseurl = "https://localhost:44337/";

        public static PassengerDetail passobj = new PassengerDetail();

        public ActionResult BookedPassenger()
        {
            return View(passobj);
        }

            public async Task<ActionResult> Index()
        {
            List<PassengerDetail> PassengerInfo = new List<PassengerDetail>();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync("api/PassengerDetails");

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var PassengerResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    PassengerInfo = JsonConvert.DeserializeObject<List<PassengerDetail>>(PassengerResponse);

                }
                //returning the employee list to view  
                return View(PassengerInfo);
            }

          
            }

        [HttpGet]

        public ActionResult Success()
        {
            return View();
        }


        [HttpGet]

        public ActionResult AddPassenger(int id, string email)
        {
            TempData["Tno"] = id;
            TempData["mail"] = email;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddPassenger(PassengerDetail e, Bookingdetails booking)
        {
            int id = (int)TempData.Peek("Tno");
            string email = (string)TempData.Peek("mail");
            e.TrainNo = id;
            e.EmailId = email;

            PassengerDetail Passobj = new PassengerDetail();
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(e), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:44337/api/PassengerDetails", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    if (apiResponse != null)
                    {
                        Passobj = JsonConvert.DeserializeObject<PassengerDetail>(apiResponse);
                    }
                   
                }
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<ActionResult> UpdatePassenger(int sno)
        {
            PassengerDetail passengers = new PassengerDetail();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44337/api/PassengerDetails" + sno))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    passengers = JsonConvert.DeserializeObject<PassengerDetail>(apiResponse);
                }
            }
            return View(passengers);
        }

        [HttpPost]
        public async Task<ActionResult> UpdatePassenger(PassengerDetail p)
        {
            PassengerDetail pass = new PassengerDetail();

            using (var httpClient = new HttpClient())
            {

                var id = p.SerialNo;
                StringContent content1 = new StringContent(JsonConvert.SerializeObject(p), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PutAsync("https://localhost:44337/api/PassengerDetails" + id, content1))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ViewBag.Result = "Success";
                    pass = JsonConvert.DeserializeObject<PassengerDetail>(apiResponse);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

TicketReservation/Views/BookingDetail/AddBookingDetail.cshtml
@model TicketReservation.Models.Bookingdetails

@{
    ViewData["Title"] = "AddBookingDetail";
}

<head>
    <link href="~/css/AddBookingDetail.css" rel="stylesheet" />
</head>



@*<style>
    #submitButton {
        border: none;
        outline: none;
        height: 60px;
        background-color: blue;
        color: whitesmoke;
        font-size: 30px;
        border-radius: 20px;
        font-family: Arial, Helvetica, sans-serif;
        border: 1px solid whitesmoke;
        width: 100%;
    }

    .registerBox input {
        width: 80%;
        border: none;
        border-bottom: 1px solid grey;
        background: transparent;
        outline: none;
        height: 30px;
        font-family: "sans-seriff";
    }

    #submitButton:hover {
        cursor: pointer;
        background-color: mediumblue;
    }

    .box {
        background-color: cornflowerblue;
        width: 500px;
        border: 20px white;
        padding: 50px;
        margin: 30px;
    }
</style>*@

<body>
        <hr />
        <div class="box">
            <div class="registerBox input">
                <form asp-action="AddBookingDetail">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    @*<div class="form-group">
                        <label asp-for="BookingId" class="control-label"></label>
                        <input asp-for="BookingId" class="form-control" />
                        <span asp-validation-for="BookingId" class="text-danger"></span>
                    </div>*@
                    <div class="form-group">
                        <label asp-for="EmailId" class="control-label"></label>
                        <input asp-for="EmailId" class="form-control" />
                        <span asp-validation-for="EmailId" class="text-danger"></span>
                    </div>
                    @*<div class="form-group">*@
                        @*  <label asp-for="TrainNo" class="control-label"></label>
                            <input asp-for="TrainNo" class="form-control" />
                            <span asp-validation-for="TrainNo" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="FromStation" class="control-label"></label>
                            <input asp-for="FromStation" class="form-control" />
                            <span asp-validation-for="FromStation" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ToStation" class="control-label"></label>
                            <input asp-for="ToStation" class="form-control" />
                            <span asp-validation-for="ToStation" class="text-danger"></span>*@
                    
                    <div class="form-group">
                        <label asp-for="JourneyDate" class="control-label"></label>
                        <input asp-for="JourneyDate" class="form-control" />
                        <span asp-validation-for="JourneyDate" class="text-danger"></span>
                       
                    </div>
                    <div class="form-group">
                        <label asp-for="NoOfSeats" class="control-label"></label>
                        <input asp-for="NoOfSeats" class="form-control" />
                        <span asp-validation-for="NoOfSeats" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BookingStatus" class="control-label"></label>
                        <input asp-for="BookingStatus" type="radio" value="ClassA" class="form-control" />ClassA
                        <input asp-for="BookingStatus" type="radio" value="ClassB" class="form-control" />ClassB
                        <input asp-for="BookingStatus" type="radio" value="ClassC" class="form-control" />ClassC
                        <span asp-validation-for="BookingStatus" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <div class="col-md-5 col-md-10">
                            <input type="submit" value="View Booking Details" class="btn btn-default" id="submitButton" />
                        </div>
                    </div>
                    @* <div class="form-group">
                        <input type="submit" value="View Booking Details" class="btn btn-primary" />
                    </div>*@
                </form>
            </div>
        </div>
        @*@Html.ActionLink("AddPassenger", "AddPassenger", "PassengerDetail", new { id = item.TrainNo, email = item.EmailId }, null)*@

       
        @*<div>
            <a asp-action="Index">Back to List</a>
        </div>*@

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }
</body>

TicketReservation/Views/BookingDetail/BookingDetails.cshtml
@model TicketReservation.Models.Bookingdetails

    <head>
        <link href="~/css/BookingDetail.css" rel="stylesheet" />
    </head>

@{
    ViewData["Title"] = "BookingDetails";
}
<body style="background-color:dimgrey">

    <h1>BookingDetails</h1>

    <div>
        <h4>Bookingdetails</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BookingId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BookingId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.EmailId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EmailId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TrainNo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TrainNo)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FromStation)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FromStation)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ToStation)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ToStation)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.JourneyDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.JourneyDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.NoOfSeats)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.NoOfSeats)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BookingStatus)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BookingStatus)
            </dd>
        </dl>
    </div>
    <div>

        @Html.ActionLink("Add Passenger", "AddPassenger", "PassengerDetail", new { id = Model.TrainNo, email = Model.EmailId })


        @*<a asp-action="Index">Back to List</a>*@
    </div>
    </body>

TicketReservation/Views/BookingDetail/GetBookById.cshtml
@model IEnumerable<TicketReservation.Models.Bookingdetails>

@{
    ViewData["Title"] = "GetBookById";
}


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookingId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrainNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FromStation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ToStation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JourneyDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoOfSeats)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookingStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BookingId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrainNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FromStation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ToStation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JourneyDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoOfSeats)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookingStatus)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>