TicketReservation/Models/ErrorViewModel.cs
using System;

namespace TicketReservation.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TicketReservation/Models/SearchTrain.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TicketReservation.Models
{
    public class SearchTrain
    {
        [Required]
        public string FromStation { get; set; }
        [Required]
        public string ToStation { get; set; }
       /* public string searchTrain { get; set; }*/
    }
}

TicketReservation/Controllers/BookingDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using TicketReservation.Models;

namespace TicketReservation.Controllers
{
    public class BookingDetailController : Controller
    {

        string Baseurl = "https://localhost:44381/";

        public static Bookingdetails book = new Bookingdetails();
        public ActionResult BookingDetails()
        {
            /* List<Bookingdetails> BookingInfo = new List<Bookingdetails>();

             using (var client = new HttpClient())
             {
                 //Passing service base url  
                 client.BaseAddress = new Uri(Baseurl);

                 client.DefaultRequestHeaders.Clear();
                 //Define request data format  
                 client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                 //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                 HttpResponseMessage Res = await client.GetAsync("/api/BookingDetails");

                 //Checking the response is successful or not which is sent using HttpClient  
                 if (Res.IsSuccessStatusCode)
                 {
                     //Storing the response details recieved from web api   
                     var bookingResponse = Res.Content.ReadAsStringAsync().Result;

                     //Deserializing the response recieved from web api and storing into the Employee list  
                     BookingInfo = JsonConvert.DeserializeObject<List<Bookingdetails>>(bookingResponse);

                 }
                 //returning the employee list to view  
                 return View(BookingInfo);
             }*/
            return View(book);
        }
        
    
    [HttpGet]
    public async Task<ActionResult> GetBookById(int id)
        {
            
            List<Bookingdetails> book = new List<Bookingdetails>();

            using (var httpClient = new HttpClient())
        {
                
                using (var response = await httpClient.GetAsync("https://localhost:44381/api/BookingDetails/" + id))
                {

                    string apiResponse = await response.Content.ReadAsStringAsync();
                    book = JsonConvert.DeserializeObject<List<Bookingdetails>>(apiResponse);

                }
            }
            return View(book);
        }


        //[HttpGet]
        //public async Task<ActionResult> BookedPassenger(int BookId)
        //{


        //    using (var httpClient = new HttpClient())
        //    {

        //        using (var response = await httpClient.GetAsync("https://localhost:44330/api/TrainDetails/" + BookId ))
        //        {

        //            string apiResponse = await response.Content.ReadAsStringAsync();
        //          //  Train = JsonConvert.DeserializeObject<List<TrainDetail>>(apiResponse);

        //        }


        //    }
        //    return View(Train);



        //}






        public ActionResult AddBookingDetail(int  id,string from,string to,int ClassA, int ClassB, int ClassC,string email)
        {
            TempData["Email"] = email;
            TempData["Tno"] = id;
            TempData["Tf"] = from;
            TempData["Tt"] = to;
            TempData["classA"] = ClassA;
            TempData["classB"] = ClassB;
            TempData["classC"] = ClassC;

            //   Bookingdetails=

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddBookingDetail(Bookingdetails booking,TrainDetail train,Register register)
        {

            string email = (string)TempData.Peek("mail");
            int id = (int)TempData.Peek("Tno");
            string from = (string)TempData.Peek("Tf");
            string to = (string)TempData.Peek("Tt");
            int ClassA = (int)TempData.Peek("classA");
            int ClassB = (int)TempData.Peek("classB");
            int ClassC = (int)TempData.Peek("classC");
            
            booking.FromStation = from;
            booking.TrainNo = id;
            booking.ToStation = to;
            train.SeatAvailA = ClassA - booking.NoOfSeats;
            train.SeatAvailB = ClassB - booking.NoOfSeats;
            train.SeatAvailC = ClassC - booking.NoOfSeats;

            
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(booking), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:44381/api/BookingDetails", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    book = JsonConvert.DeserializeObject<Bookingdetails>(apiResponse);
                }
               
            }
            return RedirectToAction("BookingDetails");
           
        }
        public bool DateCheck(Bookingdetails book)
        {
            if (book.JourneyDate < DateTime.Today)
            {

                return false;
                
            }
            else
            {
                return true;
            }
        }
        [HttpGet]
        public async Task<ActionResult> CancelTicket(int id)
        {
            TempData["BookingId"] = id;
            Bookingdetails e = new Bookingdetails();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44381/api/BookingDetails" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    e = JsonConvert.DeserializeObject<Bookingdetails>(apiResponse);
                }
            }
            return View(e);
        }


        [HttpPost]
        // [ActionName("DeleteEmployee")]
        public async Task<ActionResult> CancelTicket(Bookingdetails book)
        {
            int BookingId = Convert.ToInt32(TempData["BookingId"]);
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync("https://localhost:44381/api/BookingDetails/" + BookingId))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }

            return RedirectToAction("Index");
        }
    }
}

TicketReservation/Controllers/SearchTrainController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using TicketReservation.Models;

namespace TicketReservation.Controllers
{
    public class SearchTrainController : Controller
    {
        string Baseurl = "https://localhost:44330";

        public async Task<ActionResult> Index()
        {
            List<TrainDetail> TrainInfo = new List<TrainDetail>();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync("/api/TrainDetails");

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var TrainResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    TrainInfo = JsonConvert.DeserializeObject<List<TrainDetail>>(TrainResponse);

                }
                //returning the employee list to view  
                return View(TrainInfo);
            }
        }


      
        public ActionResult ErrorView()
        {
            return View();
        }



        [HttpGet]
        public IActionResult SearchTrain()
        {
           // ViewBag.FromList = ToSelectList(_dt, "fr", "CityName");
            return View();
        }
        [HttpPost]
        public  IActionResult SearchTrain(SearchTrain SD)
        {
            return RedirectToAction("SearchedTrain", "SearchTrain", new { from=SD.FromStation,to=SD.ToStation});
        }

        public static bool IsEmpty<T>(List<T> list)
        {
            if (list == null)
            {
                return true;
            }

            return !list.Any();
        }

        [HttpGet]
        public async Task<ActionResult> SearchedTrain(string from, string to)
        {

            List<TrainDetail> Train = new List<TrainDetail>();
            
                using (var httpClient = new HttpClient())
                {

                    using (var response = await httpClient.GetAsync("https://localhost:44330/api/TrainDetails/" + from + "," + to))
                    {

                        string apiResponse = await response.Content.ReadAsStringAsync();
                        Train = JsonConvert.DeserializeObject<List<TrainDetail>>(apiResponse);
              
                    }


                }
                if(Train.Count==0)
                {
                    return RedirectToAction("ErrorView");

                }
            return View(Train);
            
          

        }
            
        
       
           // return View();
        


       /* [HttpPost]
        public async Task<ActionResult> SearchTrain(SearchTrain e)
        {
            SearchTrain Passobj = new SearchTrain();
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(e), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:44372/api/TrainDetails ", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    Passobj = JsonConvert.DeserializeObject<SearchTrain>(apiResponse);
                }
            }
            return RedirectToAction("Index");
        }*/


    }
}

TicketReservation/Views/SearchTrain/ErrorView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}<h1> OOPS !!! Train Not Available </h1>
<h1> Check that your Source and Destination are same. <h1>

@Html.ActionLink("Return ", "SearchTrain", "SearchTrain", new { /* id=item.PrimaryKey */ })

TicketReservation/Views/SearchTrain/Index.cshtml
@model IEnumerable<TicketReservation.Models.SearchTrain>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FromStation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ToStation)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.searchTrain)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FromStation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ToStation)
            </td>
           @* <td>
                @Html.DisplayFor(modelItem => item.searchTrain)
            </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

TicketReservation/Views/SearchTrain/SearchTrain.cshtml
@model TicketReservation.Models.SearchTrain

@{
    ViewData["Title"] = "SearchTrain";
}


<style>
    #submitButton {
        border: none;
        outline: none;
        height: 50px;
        background-color: blue;
        color: whitesmoke;
        font-size: 20px;
        border-radius: 20px;
        font-family: Arial, Helvetica, sans-serif;
        border: 1px solid whitesmoke;
        width: 100%;
    }
    .registerBox input {
        width: 100%;
        border: none;
        border-bottom: 1px solid grey;
        background: transparent;
        outline: none;
        height: 30px;
        font-family: "sans-seriff";
        border-radius: 15px;
    }
   /* .registerBox input {
        width: 80%;
        border: none;
        border-bottom: 1px solid grey;
        background: transparent;
        outline: none;
        height: 30px;
        font-family: "sans-seriff";
    }*/

    #submitButton:hover {
        cursor: pointer;
        background-color: mediumblue;
    }


    .box {
        background-color: cornflowerblue;
        width: 300px;
        border: 20px white;
        padding: 50px;
        margin: 30px;
        font-family: "Comic Sans MS";
        border-radius: 15px;
    }
   /* .box {
        background-color: cornflowerblue;
        width: 500px;
        border: 20px white;
        padding: 50px;
        margin: 30px;
    }*/
</style>

@*@using (Html.BeginForm("SearchedTrain", "SearchTrain", FormMethod.Post, new { }))
{*@

    <body>
    <h1>SearchTrain</h1>
           <hr />
            <div class="box">
                <div class="registerBox input">
                    <form asp-action="SearchTrain">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="FromStation" class="control-label font-weight-bold text-dark"></label>
                            <input asp-for="FromStation" class="form-control" placeholder="Enter your Source" />
                            <span asp-validation-for="FromStation" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ToStation" class="control-label font-weight-bold text-dark"></label>
                            <input asp-for="ToStation" class="form-control" placeholder="Enter your Destination" />
                            <span asp-validation-for="ToStation" class="text-danger"></span>
                        </div>
                        @*   <div class="form-group">
                                <label asp-for="searchTrain" class="control-label"></label>
                                <input asp-for="searchTrain" class="form-control" />
                                <span asp-validation-for="searchTrain" class="text-danger"></span>
                            </div>*@
                        @* <div class="form-group">
                                <input type="submit" value="Search" class="btn btn-primary" />
                            </div>*@

                        <div class="form-group">
                            <div class="col-md-5 col-md-10">
                                <input type="submit" value="Search" class="btn btn-default" id="submitButton" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            @*<div>
                    <a asp-action="Index">Back to List</a>
                </div>*@

            @section Scripts {
                @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
            }
    
    </body>
                    

TicketReservation/Views/SearchTrain/SearchedTrain.cshtml
@model IEnumerable<TicketReservation.Models.TrainDetail>
@*@{
        ViewData["Title"] = "SearchedTrain";
        Layout = null;
    }*@

<head>
    <link href="~/css/SearchedTrain.css" rel="stylesheet" />
</head>

<h1>Trains Available</h1>
@*
    <p>
        <a asp-action="Create">Create New</a>
    </p>*@

<body style="background-color:dimgrey">
    <center>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.TrainNo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TrainName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FromStation)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ToStation)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.JourneyDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SeatAvailA)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SeatAvailB)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SeatAvailC)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FareA)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FareB)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FareC)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TrainNo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TrainName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FromStation)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ToStation)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.JourneyDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SeatAvailA)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SeatAvailB)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SeatAvailC)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FareA)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FareB)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FareC)
                        </td>
                        <td>
                            @Html.ActionLink("BookTicket Now", "AddBookingDetail", "BookingDetail", new { id = item.TrainNo, from = item.FromStation, to = item.ToStation, ClassA = item.SeatAvailA, ClassB = item.SeatAvailB, ClassC = item.SeatAvailC }, null)
                            @*    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </center>
</body>